dbt_fundamentals:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: postgres
      port: 6543
      dbname: backend
      schema: public
      threads: 4
